/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.api.JsonResponse;
import io.swagger.model.content.Transaction;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-05-21T18:10:30.703Z[GMT]")
@Api(value = "transactions", description = "the transactions API")
public interface ITransactionsApi {

    @ApiOperation(value = "transfer money.", nickname = "createTransaction", notes = "transfer money to a specified account.", response = Transaction.class, authorizations = {
            @Authorization(value = "bearerAuth")}, tags = {"Transactions",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful creation", response = Transaction.class)})
    @RequestMapping(value = "/transactions",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<JsonResponse> createTransaction(@ApiParam(value = "", required = true) @Valid @RequestBody Transaction body
    );


    @ApiOperation(value = "Get transactions.", nickname = "getTransactions", notes = "get transactions with the ability to get specific ones using filters.", response = Transaction.class, responseContainer = "List", authorizations = {
            @Authorization(value = "bearerAuth")}, tags = {"Transactions",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation.", response = Transaction.class, responseContainer = "List")})
    @RequestMapping(value = "/transactions",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<JsonResponse> getTransactions(@NotNull @ApiParam(value = "Filter transactions by IBAN.", required = true) @Valid @RequestParam(value = "IBAN", required = true) String IBAN
            , @ApiParam(value = "The number of items to skip before starting to collect the result set") @Valid @RequestParam(value = "offset", required = false) Integer offset
            , @ApiParam(value = "returns transaction(s) based on the reciever's name") @Valid @RequestParam(value = "reciever", required = false) String recieverName
            , @ApiParam(value = "Limit the number of transactions to display.", defaultValue = "20") @Valid @RequestParam(value = "limit", required = false, defaultValue = "20") Integer limit
    );

}
