/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.19).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api.interfaces;

import io.swagger.model.api.JsonResponse;
import io.swagger.model.api.LoginDetails;
import io.swagger.model.api.UserCredentials;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-05-21T18:10:30.703Z[GMT]")
@Api(value = "login", description = "the login API")
public interface ILoginApi {

    @ApiOperation(value = "login", nickname = "loginUser", notes = "login give you an access by sending you bearerToken", response = UserCredentials.class, authorizations = {
            @Authorization(value = "bearerAuth")}, tags = {"Users",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Bearer token", response = UserCredentials.class)})
    @RequestMapping(value = "/login",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<JsonResponse> loginUser(@ApiParam(value = "") @Valid @RequestBody LoginDetails body
    );

}
